name: date_calendar
version: 0.2.0
description: >
  A calendar interface and Gregorian calendar implemenation
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/dart_calendar
dev_dependencies:
  test: ^1.3.0
environment:
  sdk: '>=2.0.0-dev.8.0 <3.0.0'
