name: date_calendar
version: 0.1.6
description: >
  A calendar interface and Gregorian calendar implemenation
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/dart_calendar
documentation: 
dependencies:
dev_dependencies:
  test: any
environment:
  sdk: '>=2.0.0-dev.8.0 <3.0.0'
